config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  def index
    @notes = Note.all
  end
  
  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(notes_params)

    if @note.save
      redirect_to notes_path
    else
      render :new
    end
      
  end

  def edit
    @note = Note.find(params[:id])
  end
  
  def update
    @note = Note.find(params[:id])

    if @note.update(notes_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy
    # Note.destroy(params[:id])
    # puts Note.find(params[:id])
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

private

  def notes_params
    params.require(:note).permit(:title, :author, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Notes', notes_path %>
<hr></hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#delete</h1>
<p>Find me in app/views/notes/delete.html.erb</p>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%# <%  binding.pry %> 
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<h1> Notes </h1>
<% @notes.each do |note| %>
  <%# <%= binding.pry %>
  <h2><%= note.title %></h2>
  <%= link_to 'Show', note_path(note) %>
  <%= link_to 'Edit', edit_note_path(note) %>
  <%= link_to 'Delete', note, method: :delete %>
<% end %>
<p><%= link_to 'New Note', new_note_path %></p>

app/views/notes/new.html.erb
<h1>New Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<h1><%= @note.title %></h1>
<h4><%= @note.author %></h1>
<p><%= @note.body %></p>
<%= link_to 'Back', notes_path %>

app/views/static_pages/about.html.erb
<h1>Virtual Post-It Notes</h1>
<p>This application allows you to save notes to the master list in the PostgresQL Database.</p>

app/views/static_pages/home.html.erb
<h1>Virtual Post-It Notes</h1>
<img class="images_home" alt="post-its" src="./post_its.jpg"/>
<p><%= link_to 'New Note', new_note_path %></p>
<p><%= link_to 'All Notes', notes_path %></p>
<%# <% binding.pry %>